# Generated by Django 3.2.3 on 2021-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminuname', models.CharField(max_length=20)),
                ('adminpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
